# Generated by Django 5.1.3 on 2024-12-11 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0003_classmodel_remove_subject_assigned_class_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.classmodel'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.subjectmodel'),
        ),
    ]
