# Generated by Django 5.1.3 on 2024-12-11 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('grade', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assigned_class',
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='hod.classmodel'),
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='hod.classmodel')),
            ],
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='hod.subjectmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'subject', 'assigned_class')},
        ),
    ]
