# Generated by Django 5.1.3 on 2024-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_delete_class_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
