# Generated by Django 5.1.3 on 2024-12-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject_id', models.IntegerField()),
                ('class_id', models.IntegerField()),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
